version: 0.2

env:
  variables:
    AWS_REGION: ap-southeast-2
    ECR_REPOSITORY: aceautomation/expensemanagertests
    ECS_CLUSTER: expensemanager-test-cluster
    ECS_TASK_DEFINITION: expensemanager-test-task
    S3_BUCKET: ace-automation-bucket-2026-ap-southeast-2

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URI/$ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_URI/$ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Updating ECS Task Definition...

      - TASK_DEF=$(aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION)
      - NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$ECR_URI/$ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION" '.taskDefinition | .containerDefinitions[0].image=$IMAGE | del(.taskDefinitionArn,.revision,.status,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy)')

      - echo "$NEW_TASK_DEF" > new-task-def.json

      - TASK_REVISION=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)

      - echo "Running ECS task..."

      - TASK_ARN=$(aws ecs run-task \
        --cluster $ECS_CLUSTER \
        --launch-type FARGATE \
        --task-definition $TASK_REVISION \
        --query 'tasks[0].taskArn' \
        --output text)

      - echo "Waiting for task to stop..."

      - aws ecs wait tasks-stopped --cluster $ECS_CLUSTER --tasks $TASK_ARN

      - EXIT_CODE=$(aws ecs describe-tasks --cluster $ECS_CLUSTER --tasks $TASK_ARN --query 'tasks[0].containers[0].exitCode' --output text)

      - echo "Exit Code: $EXIT_CODE"

      - |
        if [ "$EXIT_CODE" != "0" ]; then
          echo "ECS Tests Failed"
          exit 1
        fi